// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUit9gk1-lAZ1K59fm63Qww2C2XFVjbjE',
    appId: '1:544545782245:web:8838ede42ddda97110d70c',
    messagingSenderId: '544545782245',
    projectId: 'heart-to-heart-e98f6',
    authDomain: 'heart-to-heart-e98f6.firebaseapp.com',
    storageBucket: 'heart-to-heart-e98f6.firebasestorage.app',
    measurementId: 'G-93SZH6LCQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDinsrPVwsMHKmW-D7b3GjifcuDHkGYHSM',
    appId: '1:544545782245:android:6f320ae8a540fd0e10d70c',
    messagingSenderId: '544545782245',
    projectId: 'heart-to-heart-e98f6',
    storageBucket: 'heart-to-heart-e98f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhZytQc05X44pE6cb6tPuCuUjf5kVfyE',
    appId: '1:544545782245:ios:1ed2aa40ef783d6f10d70c',
    messagingSenderId: '544545782245',
    projectId: 'heart-to-heart-e98f6',
    storageBucket: 'heart-to-heart-e98f6.firebasestorage.app',
    iosClientId: '544545782245-ljreeiql8oam5e33cg8nl9gjcp4qpo1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.heartToHeart',
  );
}
